# Generated by Django 2.2.1 on 2019-06-09 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=30, verbose_name='Definition')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=255, verbose_name='Definition')),
                ('translation', models.CharField(max_length=255, verbose_name='Translation')),
                ('partOfSpeech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.PartOfSpeech')),
            ],
        ),
    ]
